
version: "3"

volumes:
  dbbackups:
  postgis-data:

services:
  statistic-service:
    build: .
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - default
    volumes:
      - $PWD/media:/app/media
    depends_on:
      - statistic-bd

  statistic-bd:
    image: kartoza/postgis:12.0
    expose:
      - "5432"
    volumes:
      - ./scripts/initBD.sql:/docker-entrypoint-initdb.d/init.sql
      - postgis-data:/var/lib/postgresql
    env_file:
      - envs/postgres.env
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"