#statistic_bd = "host=statistic-bd port=5432 user=andrewkireev dbname=statistic_bd password=password sslmode=disable"
statistic_bd = "host=localhost port=5432 user=andrewkireev dbname=avitoadvertising sslmode=disable"