// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock_statistic is a generated GoMock package.
package mock_statistic

import (
	models "AvitoTask/internal/app/statistic/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// DeleteAll mocks base method.
func (m *MockRepository) DeleteAll() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAll")
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAll indicates an expected call of DeleteAll.
func (mr *MockRepositoryMockRecorder) DeleteAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MockRepository)(nil).DeleteAll))
}

// GetStatistic mocks base method.
func (m *MockRepository) GetStatistic(arg0, arg1, arg2 string) ([]models.Statistic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatistic", arg0, arg1, arg2)
	ret0, _ := ret[0].([]models.Statistic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatistic indicates an expected call of GetStatistic.
func (mr *MockRepositoryMockRecorder) GetStatistic(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatistic", reflect.TypeOf((*MockRepository)(nil).GetStatistic), arg0, arg1, arg2)
}

// SaveStatistic mocks base method.
func (m *MockRepository) SaveStatistic(arg0 *models.Statistic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveStatistic", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveStatistic indicates an expected call of SaveStatistic.
func (mr *MockRepositoryMockRecorder) SaveStatistic(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveStatistic", reflect.TypeOf((*MockRepository)(nil).SaveStatistic), arg0)
}
